# Generated by Django 5.2.3 on 2025-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumptions',
            name='closing_balance',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
