# Generated by Django 5.2.3 on 2025-06-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50)),
                ('chemical_code', models.CharField(max_length=50)),
                ('chemical_name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('unit_code', 'chemical_code'), name='unique_unit_code_chemical_code')],
            },
        ),
        migrations.CreateModel(
            name='DailyConsumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.FloatField()),
                ('reciept', models.FloatField()),
                ('consumption', models.FloatField()),
                ('sap', models.FloatField()),
                ('chemical_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_consumptions_chemical', to='chemical_management.chemicalmaster')),
                ('unit_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_consumptions_unit', to='chemical_management.chemicalmaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'unit_code', 'chemical_code'), name='unique_date_unit_chemical')],
            },
        ),
    ]
