# Generated by Django 5.2.3 on 2025-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_management', '0002_dailyconsumptions_closing_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumptions',
            name='remarks',
            field=models.CharField(default='No Remarks', max_length=255),
        ),
    ]
